---
created: 2023-11-03T22:29
updated: 2023-11-06T12:24
---
# 1. async/await

async/await 是以更舒适的方式使用 promise 的一种特殊语法，同时它也非常易于理解和使用。

## 1.1. [async function](https://zh.javascript.info/async-await#asyncfunction)

* 让我们以 `async` 这个关键字开始。它可以被放置在一个函数前面，如下所示：

```js
async function f() { 
	return 1; 
}
```

* 在函数前面的 “async” 这个单词表达了一个简单的事情：即这个函数总是返回一个 promise。其他值将自动被包装在一个 resolved 的 promise 中。
![[Pasted image 20231026160637.png]]
* ……我们也可以显式地返回一个 promise，结果是一样的：
![[Pasted image 20231026160648.png]]

* 所以说，`async` 确保了函数返回一个 promise，也会将非 promise 的值包装进去。
* 很简单，对吧？但不仅仅这些。还有另外一个叫 `await` 的关键词，它只在 `async` 函数内工作，也非常酷。

## 1.2. [await](https://zh.javascript.info/async-await#await)

* 语法如下：
```js
// 只在 async 函数内工作
let value = await promise;
```

* 关键字 `await` 让 JavaScript 引擎等待直到 promise 完成（settle）并返回结果。

* 这里的例子就是一个 1 秒后 resolve 的 promise：

```html
<!DOCTYPE html>
<script>
"use strict";

async function f() {

  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });

  let result = await promise; // 等待，直到 promise resolve (*)

  alert(result); // "done!"
}

f();
</script>

```

* 这个函数在执行的时候，“暂停”在了 `(*)` 那一行，并在 promise settle 时，拿到 `result` 作为结果继续往下执行。所以上面这段代码在一秒后显示 “done!”。

* 让我们强调一下：`await` 实际上会暂停函数的执行，直到 promise 状态变为 settled，然后以 promise 的结果继续执行。这个行为不会耗费任何 CPU 资源，因为 JavaScript 引擎可以同时处理其他任务：执行其他脚本，处理事件等。

* 相比于 `promise.then`，它只是获取 promise 的结果的一个更优雅的语法。并且也更易于读写。
* ![[Pasted image 20231026161209.png]]
* 让我们拿 [Promise 链](https://zh.javascript.info/promise-chaining) 那一章的 `showAvatar()` 例子，并将其改写成 `async/await` 的形式：
	1. 我们需要用 `await` 替换掉 `.then` 的调用。
	2. 另外，我们需要在函数前面加上 `async` 关键字，以使它们能工作。
	3. 
```html
<!DOCTYPE html>
<script>
"use strict";

async function showAvatar() {

  // 读取我们的 JSON
  let response = await fetch('/article/promise-chaining/user.json');
  let user = await response.json();

  // 读取 github 用户信息
  let githubResponse = await fetch(`https://api.github.com/users/${user.name}`);
  let githubUser = await githubResponse.json();

  // 显示头像
  let img = document.createElement('img');
  img.src = githubUser.avatar_url;
  img.className = "promise-avatar-example";
  document.body.append(img);

  // 等待 3 秒
  await new Promise((resolve, reject) => setTimeout(resolve, 3000));

  img.remove();

  return githubUser;
}

showAvatar();
</script>

```
* ![[Pasted image 20231026161422.png]]
* ![[Pasted image 20231026161434.png]]
* ![[Pasted image 20231026161542.png]]

## 1.3. [Error 处理](https://zh.javascript.info/async-await#error-chu-li)

* 如果一个 promise 正常 resolve，`await promise` 返回的就是其结果。
* 但是如果 promise 被 reject，它将 throw 这个 error，就像在这一行有一个 `throw` 语句那样。
* ![[Pasted image 20231026161711.png]]
* 在真实开发中，promise 可能需要一点时间后才 reject。在这种情况下，在 `await` 抛出（throw）一个 error 之前会有一个延时。
* 我们可以用 `try..catch` 来捕获上面提到的那个 error，与常规的 `throw` 使用的是一样的方式:
* 
  ```html
  <!DOCTYPE html>
<script>
"use strict";

async function f() {

  try {
    let response = await fetch('http://no-such-url');
  } catch(err) {
    alert(err); // TypeError: failed to fetch
  }
}

f();
</script>

```
* 如果有 error 发生，执行控制权马上就会被移交至 `catch` 块。我们也可以用 `try` 包装多行 `await` 代码:
* 
  ```html
  <!DOCTYPE html>
<script>
"use strict";

async function f() {

  try {
    let response = await fetch('/no-user-here');
    let user = await response.json();
  } catch(err) {
    // 捕获到 fetch 和 response.json 中的错误
    alert(err);
  }
}

f();
</script>

```
* 如果我们没有 `try..catch`，那么由异步函数 `f()` 的调用生成的 promise 将变为 rejected。
* 我们可以在函数调用后面添加 `.catch` 来处理这个 error：
* 
  ```html
  <!DOCTYPE html>
<script>
"use strict";

async function f() {
  let response = await fetch('http://no-such-url');
}

// f() 变成了一个 rejected 的 promise
f().catch(alert); // TypeError: failed to fetch // (*)
</script>

```
* 如果我们忘了在这添加 `.catch`，那么我们就会得到一个未处理的 promise error（可以在控制台中查看）。
* 我们可以使用在 [使用 promise 进行错误处理](https://zh.javascript.info/promise-error-handling) 一章中所讲的全局事件处理程序 `unhandledrejection` 来捕获这类 error。
* ![[Pasted image 20231026162732.png]]
* ![[Pasted image 20231026162740.png]]

## [总结](https://zh.javascript.info/async-await#zong-jie)

函数前面的关键字 `async` 有两个作用：

1. 让这个函数总是返回一个 promise。
2. 允许在该函数内使用 `await`。

Promise 前的关键字 `await` 使 JavaScript 引擎等待该 promise settle，然后：

1. 如果有 error，就会抛出异常 —— 就像那里调用了 `throw error` 一样。
2. 否则，就返回结果。

这两个关键字一起提供了一个很好的用来编写异步代码的框架，这种代码易于阅读也易于编写。

有了 `async/await` 之后，我们就几乎不需要使用 `promise.then/catch`，但是不要忘了它们是基于 promise 的，因为有些时候（例如在最外层作用域）我们不得不使用这些方法。并且，当我们需要同时等待需要任务时，`Promise.all` 是很好用的。


![[Pasted image 20231026163159.png]]
```html
<!DOCTYPE html>
<script>
"use strict";

async function loadJson(url) { // (1)
  let response = await fetch(url); // (2)

  if (response.status == 200) {
    let json = await response.json(); // (3)
    return json;
  }

  throw new Error(response.status);
}

loadJson('https://javascript.info/no-such-user.json')
  .catch(alert); // Error: 404 (4)
</script>

```
![[Pasted image 20231026162953.png]]

```html
<!DOCTYPE html>
<script>
"use strict";

class HttpError extends Error {
  constructor(response) {
    super(`${response.status} for ${response.url}`);
    this.name = 'HttpError';
    this.response = response;
  }
}

async function loadJson(url) {
  let response = await fetch(url);
  if (response.status == 200) {
    return response.json();
  } else {
    throw new HttpError(response);
  }
}

// 询问用户名，直到 github 返回一个合法的用户
async function demoGithubUser() {

  let user;
  while(true) {
    let name = prompt("Enter a name?", "iliakan");

    try {
      user = await loadJson(`https://api.github.com/users/${name}`);
      break; // 没有 error，退出循环
    } catch(err) {
      if (err instanceof HttpError && err.response.status == 404) {
        // 循环将在 alert 后继续
        alert("No such user, please reenter.");
      } else {
        // 未知的 error，再次抛出（rethrow）
        throw err;
      }
    }
  }


  alert(`Full name: ${user.name}.`);
  return user;
}

demoGithubUser();
</script>

```

```html
<!DOCTYPE html>
<script>
"use strict";

async function wait() {
  await new Promise(resolve => setTimeout(resolve, 1000));

  return 10;
}

function f() {
  // 1 秒后显示 10
  wait().then(result => alert(result));
}

f();
</script>

```